name: CI
on: [push]
jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 20.20.2
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Code formatting
        run: yarn fmt:check

      - name: Typescript build
        run: yarn build
