name: CI
on: [push]
jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 20.19.5
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Code formatting
        run: yarn fmt:check

      - name: Typescript build
        run: yarn build
